### ISSUE TITLE
Nodejs adding attachment without filename

### ISSUE THREAD

**Issue by ovesco** [pryv/lib-js#41]
Hello,
I'm trying to create an event with a picture attached in Nodejs, but not from a file, as it is coming from a PubSub system in a base64 encoded string. I tried the following:
```js
const image = ""; // My image in base64

// 1.
await connection.createEventWithFile({
  type: 'picture/attached',
  streamId: 'my-stream'
}, image); // --> error as expected

// 2.
await connection.createEventWithFile({
  type: 'picture/attached',
  streamId: 'my-stream'
}, Buffer.from(image)); // --> no attachment in event

// 3.
await connection.api([
  // ...
  {
    method: "events.create",
    params: {
      streamId: 'my-stream',
      type: "picture/base64",
      content: {
        payload: image,
        format: 'jpg',
        filename: 'my-picture.jpg'
      }
    }
  }
]); // -> event.content === '[object Object]', do I do something wrong here?
```

I also tried using the [Nodejs form-data module](https://www.npmjs.com/package/form-data) but it didn't work well with `superagent`.

Do you have any solution ?

**Comment by perki** [comment]
@ovesco Yes FormData model does not work well with super agent. 
If you look at https://github.com/pryv/lib-js/blob/a4922bf3c6e63a69e7fe46db7ccf73a4c6b7adc5/src/Connection.js#L250 
You see that the "attachment" is forced to a file type. 

I would try with `conn._post('events').field('event', JSON.stringify('event')).attach('file', buffer data, filename);`

**Comment by perki** [comment]
@ovesco 
Hello, we added connection.createEventWithFileFromBuffer() that will do what you want.. 
We didn't test with a Base64 buffer, you will probably need to decode your data before.
